name: Daily 데이터 생성

on:
  push:
    branches: ['main']
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PRIVATE_GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Modules
        run: yarn install

      - name: Generate Data
        run: yarn run update:data

      - name: Push Data
        run: |
          CURRENT_DATE=$(date +%Y%m%d%H%m)

          git config --global user.email "iot.frontier@gmail.com"
          git config --global user.name "jongju park"

          # 변경 사항이 있을 때만 커밋 및 푸시 수행
          if [[ `git status --porcelain` ]]; then
            git fetch origin
            git add -A
            git commit -am "Update notion data : ${CURRENT_DATE}"
            git push origin main
          fi
